name: freedomotic
architecture: armhf
version: 5.6.0
vendor: Freedomotic Team <info@freedomotic.com>
icon: meta/freedomotic.svg
services:
 - name: freedomotic
   description: "freedomotic runtime"
   start: bin/start
   caps:
     - network-service
binaries:
 - name: start
   exec: bin/start
   description: "freedomotic runtime cli"
   caps:
     - network-service

